### ISSUE TITLE
Snippets shown in intellisense

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#105]
Almost there with the intellisense :-)

In the latest version there's still sometimes that intellisense shows up with snippet suggestions, although I can't pinpoint when. Here are some example cases when I type ``op`` after hitting "." : -

| Namespace / Type | Expected | Actual |
| ------------- | ------------- | ---------- |
| System  | OperatingSystem | OperatingSystem |
| System.IO | `<no suggestions>` | open, optional etc. etc. |
| Expr | `<no suggestions>` | open ,optional etc. etc. |

It *seems* like if the namespace or type has *some* elements in it that match the first letter, it's first, but if you put a letter that *doesn't* contain any elements, it will fall back to the snippet stuff.

**Comment by Krzysztof-Cieslak** [comment]
Yeah, looks like it's not connected to keywords, but rather to some problems with triggering autocomplete - looks like VSCode decide sometimes to use its built-in autocomplete (all words from current file) instead of autocomplete provided by Ionide.

 It's bit weird, don't know exact reason why it's happening yet.

**Comment by Krzysztof-Cieslak** [comment]
Problem can be reduced by setting `"editor.wordBasedSuggestions": false` in user or workspace settings file

**Comment by Krzysztof-Cieslak** [comment]
I think that `"editor.wordBasedSuggestions": false` solves this problem well enough, closing for now.

**Comment by isaacabraham** [comment]
Cool, thanks for the tip
