### ISSUE TITLE
Does not build on Linux/Mono

### ISSUE THREAD

**Issue by hyperlobic** [ionide/ionide-vscode-fsharp#11]
I'm getting a compile error when running build.sh on Linux with Mono 4.2: 

`A namespace and a module named 'Ionide.VSCode' both occur in two parts of this assembly`

If I remove the Mono specific stuff in build.fsx it works fine. Any reason why a separate build process is needed?

**Comment by Krzysztof-Cieslak** [comment]
Build process is copied from Atom Ionide-fsharp project and... I actually don't know why there were any specific parts for Mono - as far as I remember there were some problems with Mono which forced us to create different building path, but maybe it got fixed in latest mono release. All main contributors are Windows developers.

Feel free to PR changes to make it building using Mono :)
