### ISSUE TITLE
Omnisharp detects 29K+ problems using paket: generate_load_scripts

### ISSUE THREAD

**Issue by davidspiess** [ionide/ionide-vscode-fsharp#1111]
**Describe the bug**
I use `generate_load_scripts: true` in my paket.dependencies to import netstandard in my fsx files.

```c#
﻿#r "netstandard"
#load @"../../.paket/load/netstandard2.0/main.group.fsx"
```
Omnisharp type checks the whole .paket/load directory for errors and finds 29K+ problems. The folder is gitignored and i tried to add .paket to the exluded project directories, but it had no effect.

```json
    "FSharp.excludeProjectDirectories": [
        ".git",
        "paket-files",
        ".fable",
        "node_modules",
        ".paket"
    ]
```

The whole typechecking takes a long time and until the process is finished, no intellisense shows up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install dependencies with paket
2. Use `generate_load_scripts: true`  to create the .paket/load directory

**Screenshots**
![image](https://user-images.githubusercontent.com/992674/58229992-669ed480-7d33-11e9-9da3-e2576ba63c1d.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Enterprise 1709
 - Ionide version: 1.34.0 
 - VSCode version: 1.34.0
 - dotnet SDK version: 2.2.300
 - mono / .Net Framework version:  4.6.1

**Comment by vbfox** [comment]
While ionide might be affected for sure, In your screenshot the errors are from `.csx` files that are handled by Omnisharp, not ionide.

**Comment by davidspiess** [comment]
Hi @vbfox, thanks for pointing that out! I changed the description.

**Comment by drk-mtr** [comment]
David I think what vbfox is highlighting is that you would need to raise this issue on a different repository i.e. it is not something within Ionide's control. I doubt it will be accepted as an Omnisharp issue either unfortunately, because any Omnisharp doesn't formally support F#.

I would guess that your issue can be closed and that you'll just need to keep an eye on the progress of this one: https://github.com/OmniSharp/omnisharp-vscode/issues/1694 or investigate other Omnisharp exclude settings.

**Comment by davidspiess** [comment]
@drk-mtr thanks for the explanation! I didn't know about Omnisharp, so i will close this in favor of the referenced issue!
