### ISSUE TITLE
Change "File not in project" status bar item when we're still restoring/loading projects

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#1130]
When you open a project that hasn't been restored or cached it may take a while before we parse all projects.
During this time we can report open filed as "not in project" while in reality we just don't know about it yet - the message is misleading. We should probably change a message a bit while any project is still restoring/loading.

**Comment by Krzysztof-Cieslak** [comment]
This should be worked on `4.0` branch

**Comment by tenigma** [comment]
So, I actually cannot reproduce this.
I created 20 project files in one directory, opened two files, one from the first project and one from the last. I looked at the status bar and I saw the message "Project loading" but the message "Not in a F# project" never came up.
How can I reproduce this?

**Comment by forki** [comment]
Create an sln file and just don't add the project to it. Ionide 4 is
parsing the sln if it exists and only loads projects that are listed over
there

Tomas Leko <notifications@github.com> schrieb am So., 16. Juni 2019, 10:49:

**Comment by tenigma** [comment]
OK, this I can reproduce but I guess in such a case the message should be there. The tooltip also says "Library.fs is not in any project known to ionide" which is correct I guess.
Sorry, but I just don't understand what is current behaviour and what is expected behaviour of this issue.
Please correct me if I am wrong. I understood this issue as:

1. Open an ionide workspace (Solution or directory) in VSCode
2. Ionide starts to parse all projects from the workspace
3. While ionide is loading all the projects open an F# file which is in some of the currently loading projects
4. Look at status bar and see the message "Not in a F# project" which is actually incorrect and should not be shown at this point in time

Maybe I complicate to much and maybe this issue is just changing of the message "Not in a F# project" to something else?

Sorry, but I am new to contributing and I don't know how this works. I hope I am not taking to much of your time.

**Comment by Krzysztof-Cieslak** [comment]
I think #1130 was all we needed. Eventually we can try handling situation where workspace is not yet loaded, and file is not in project (yet?) with some other message.
