### ISSUE TITLE
Ionide 4 does not detect external changes in fsproj

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1143]
1. Open a xyz.fs from a .fsproj
2. Change and save the .fsproj (e.g. file order) so that the xyz.fs would have compile error
3. Observe that the ionide does not show those errors in xyz.fs
4. make a random change in xyz.fs and see how the errors are shown

This is a regression to Ionide 3

**Comment by Krzysztof-Cieslak** [comment]
I can't repro that on latests experimental.

**Comment by jackfoxy** [comment]
I think this is my problem.

Reproduction steps.

1) From PowerShell CD'ed into project folder
code .

2) Do some stuff in *.fs (the case I see is with a fable project, the client App.fs file)
(it is possible I am leaving unsaved changes, but I don't think so)
Do not close file in Code/Ionide.

3) close Code

4) Make changes to same *.fs file in another editor. (In my case Visual Studio 2019 preview 2.) Close editor

5) start from powershell again

6) Note *.fs file is in last state it was previously in in code, marked as pending changes (dot instead of X)

Workaround is to close file in Code/Ionide and re-open.

@Krzysztof-Cieslak  @forki

**Comment by jackfoxy** [comment]
Pretty sure in my case I have left the project buildable in all editors when closing.

**Comment by jackfoxy** [comment]
I am seeing this in my local version of the SAFE-dojo project
