### ISSUE TITLE
Project loading is sequential and it take ages.

### ISSUE THREAD

**Issue by Szer** [ionide/ionide-vscode-fsharp#1148]
**Is your feature request related to a problem? Please describe.**

Trying to open big solution (~160 projects) with Ionide 4.0.0
Projects are loading one-by-one (even if they are independent from each other) and it takes ages to finish.

**Describe the solution you'd like**
They should load in parallel. Even if some work could be done twice, it's worth doing.

**Describe alternatives you've considered**
Rider does "synchronization project" initialization in 2 minutes with going extreme load with SSD and CPU.

**Comment by matthid** [comment]
Problem for @Krzysztof-Cieslak is that then I'm complaining about CPU usage (and unusable system) when opening `Fake.sln` ;)

**Comment by Krzysztof-Cieslak** [comment]
Changes in a project parsing strategy are planned for the future. @enricosada knows more about that

**Comment by 7sharp9** [comment]
With 160 projects sounds like you have bigger issues to think about first  :-)

**Comment by matthid** [comment]
@7sharp9 160 doesn't sound like a number a computer cannot handle either. I think it should work. Saying that's too much is not reasonable when Microsoft internally tests VS against such numbers and therefore all other editors can work with that number just fine.

**Comment by Krzysztof-Cieslak** [comment]
> when Microsoft internally tests VS against such numbers

If I get whole team working just on project system it will be reasonable to expect Ionide supporting such amounts without any problem ;-)

**Comment by enricosada** [comment]
Yes, there are various enhancement we can do to reach that goal eventually.
For sure i think we can incrementally improve, one step at time, i hope to do so.

**Comment by voronoipotato** [comment]
Honestly I unironically hope we don't support 160 projects in a single solution. The cognitive load of that sounds bad. Multiple solutions is not a crime. Supporting so many projects in a solution is in itself a footgun and leads to a scenario where I could theoretically work there.

**Comment by matthid** [comment]
![image](https://user-images.githubusercontent.com/1866463/60626545-69d5b780-9deb-11e9-9d4e-8ee4512f9846.png)

And I already have a lots of tooling issues ;)
I don't feel any cognitive load to be honest. In fact it's a lot easier to find stuff now than it was with "FakeLib" (imho)

**Comment by Krzysztof-Cieslak** [comment]
TBF, I’m just not sure how well we can support such loads - not only in terms of just a project loading (improvements here will affect everyone, even smaller projects) but just in terms of FCS/FSAC/BackgroundService performance

**Comment by voronoipotato** [comment]
I'm currently looking at a solution with millions of lines with half as many projects. It needs to be broken up into more than one solution.

**Comment by matthid** [comment]
@Krzysztof-Cieslak I don't see any reason why it wouldn't work. The issues I currently see are not mainly performance to be honest. Yes startup perf is an issue but even once everything is loaded I run into lots of issues I'm trying to figure out and report properly, but I don't see any high load after everything is loaded. This has drastically improved from 3 to 4

Problems are more like:
- Everything suddenly stops working (intellisense, line lense, ...) after some hours <- I see this on small solutions as well
- I think there is an issue with multi-targeting which I'm trying to figure out which breaks some stuff
- Issues I have already reported on various locations
- Sometimes FSAC seems to decide it needs to reload everything. I feel like this happens when you run a `fake build`, maybe all project files are touched and Ionide goes crasy about that (even if there are no actual changes). This obviously is much worse if you have lots of projects.

Back to this issue: I don't see anything we couldn't work out.

**Comment by voronoipotato** [comment]
For the record I talked to @matthid  on slack and better understand why his project is the way it is :). The moral of the story is don't comment if you haven't gotten a full night's rest.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed with 5.0

The project loading is still sequential but should be way faster
