### ISSUE TITLE
Can't create project on MacOS Mojave

### ISSUE THREAD

**Issue by chespinoza** [ionide/ionide-vscode-fsharp#1162]
**Describe the bug**
Can't create project on MacOS Mojave

**To Reproduce**
Steps to reproduce the behaviour:
0. From new empty folder open vscode
1. From command palette  Click on `F# New Project (ProjectScaffold)`
2. vscode returns `Creating Project fails - directory is not empty`

**Expected behaviour**
Create project files

**Screenshots**
![Screenshot 2019-06-30 at 12 25 55](https://user-images.githubusercontent.com/3278356/60395909-42a09100-9b32-11e9-84ae-04e3785df408.png)

**Environment (please complete the following information):**
 - OS: MacOS Mojave 10.14.5
 - Ionide version: 4.0.0
 - VSCode version: 1.35.1
 - dotnet SDK version:
```
NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
``` 
- mono / .Net Framework version:
```
Mono JIT compiler version 5.18.1.3 (2018-08/fdb26b0a445 Wed Mar 20 10:02:02 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```
**Additional context**

**Comment by Krzysztof-Cieslak** [comment]
I can reproduce. This one is tricky:
* Creating ProjectScaffold template is done by running `git clone`
* Cloning into an existing directory is only allowed if the directory is empty. - from git documentation
* When we activate Ionide (while FSAC startup to be specific) we create (if it doesn't exist) `.ionide`  folder with `symbolCache.db` file... and hence we're making directory non empty
* Since directory is non empty, clone file

There are some workarounds possible that would involve running different git commands to obtain ProjectScaffold template.

**Comment by Krzysztof-Cieslak** [comment]
We don't support `ProjectScaffold` template any more
