### ISSUE TITLE
netstandard related intellisense errors with netcore 3.1.0

### ISSUE THREAD

**Issue by fwaris** [ionide/ionide-vscode-fsharp#1266]
Using netcore and "useSdkScripts", the intellisense is giving following errors on  a script that references  "netstandard".

(no issue when running the code in fsi)

Problem reading assembly 'C:\Program Files\dotnet\shared/Microsoft.NETCore.App\3.1.0\Microsoft.DiaSymReader.Native.amd64.dll': The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Error opening binary file 'C:\Program Files\dotnet\shared/Microsoft.NETCore.App\3.1.0\Microsoft.DiaSymReader.Native.amd64.dll': C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.0\Microsoft.DiaSymReader.Native.amd64.dll: bad cli header, rva 0)F# Compiler(3160)

**Comment by baronfel** [comment]
Thanks for reporting, it looks like you're being forced to use the actual implementation assemblies instead of the 'reference' assemblies that are shipped with the SDK. We'll have to install the SDK and take a look to see what/if anything has changed.

**Comment by Krzysztof-Cieslak** [comment]
@baronfel, have you fixed that in recent FSAC updates?

**Comment by baronfel** [comment]
Yes this should handle 3.1 better now.

**Comment by CVertex** [comment]
I've just started to get into F# on my new windows 10 machine. It's been a while since I did any .net coding, but i'm looking forward to getting back into it again.

When I follow the [instructions ](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode)for VSCode, Windows, F# .net core 3.1, I see this error in my fsx file too.

I've installed all the latest bits as of 18th Jan.. 

Do you have enough information to debug this? What else do you need from me to help diagnose and fix this?
