### ISSUE TITLE
Not loading symbols from paket-file-source (in reasonable time)

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#127]
<img width="240" alt="screen shot 2016-08-07 at 19 41 16" src="https://cloud.githubusercontent.com/assets/193115/17464121/11ad2834-5cd7-11e6-9a9d-a7657217fbf5.png">

With the version current at time of writing, open Suave, and e.g. the file SuaveConfig.fs. It won't find Facade.fs

**Comment by cloudRoutine** [comment]
For future reference when something goes wrong with Ionide and you want to try to identify the source set
```
"FSharp.logLanguageServiceRequestsToConsole": true,
```
in your `settings.json` and check the log of the developer tools.

![](http://i.imgur.com/VXPPnnM.png)

![](http://i.imgur.com/dLA6ZQL.png)

I'm not sure if the error is on our end or in FSAC, but I'll investigate it

**Comment by cloudRoutine** [comment]
@haf  I'm getting the same errors in visual studio as I was in vscode

![](http://i.imgur.com/G6zBd8k.png)

**Comment by haf** [comment]
@cloudRoutine Thanks for testing for me. I can successfully build it with `bundle exec rake` which fixes the naming initially. After that the editor should work.

**Comment by haf** [comment]
I just tested this with another project. Waiting a longer period of time makes it go away it would seem.

**Comment by Krzysztof-Cieslak** [comment]
Original @haf's post from #113:

## Description

When working with large projects, like Logary, code-completion and tool-tips work as long as it all compiles. After a few minutes working, breaking things as one types new code or change type declarations, the tooltips stop working, even when closing and opening the file again.

## Expected behaviour

To work

## Actual behaviour

A 'Loading...' message is displayed.


## Steps to reproduce

Start logary, hack away at a new target for a while, watch tooltips disappear.

## Other observations

Sometimes tool-tips are "off" i.e. the red squigglies are under the wrong characters (not a full symbol is underlined).

Sometimes the tool-tips take a really long time to start showing, initially.

**Comment by Krzysztof-Cieslak** [comment]
Can you try latest version? Latest FSAC / FCS version is bit faster and should handle big projects bit better

**Comment by deapsquatter** [comment]
Added a video of my experience with ionide. The video shows extremely long processing times for new code. Adding a simple function can take minutes to clear. VS Code was started fresh for the video. See mono CPU utilization in task window.
[Youtube - ionide performance issue
](https://youtu.be/MEeuXQhEpUw)

**Comment by Krzysztof-Cieslak** [comment]
@deapsquatter: Can you create issue about this on https://github.com/fsharp/FsAutoComplete ? Thanks.

**Comment by deapsquatter** [comment]
Thanks. Added here [https://github.com/fsharp/FsAutoComplete/issues/105](https://github.com/fsharp/FsAutoComplete/issues/105)

**Comment by Krzysztof-Cieslak** [comment]
I believe that performance should be better in general given latest optimization in compiler / FCS.
