### ISSUE TITLE
Update documentation to explain how to get Ionide working for .fsx files

### ISSUE THREAD

**Issue by drk-mtr** [ionide/ionide-vscode-fsharp#1347]
Ionide doesn't work out of the box for .fsx files as per this closed issue:

https://github.com/ionide/ionide-vscode-fsharp/issues/1300

Are you ok for me to submit a small PR to add a note to documentation to explain how to get this working, and if so where would the most appropriate place be? The Ionide docs page (http://ionide.io/docs) is currently a 404 for me so I wasn't sure how to check whether this is already mentioned.

**Comment by Krzysztof-Cieslak** [comment]
Ionide is working out of the box for `.fsx` files - the linked issue was a problem with detecting correct .Net SDK root on Linux which got fixed in some previous release.

However, more docs are always appreciated. Docs page got recently merged with main ionide page (and it's https://ionide.io) and it's here https://github.com/ionide/ionide.github.io/tree/dev. Please open the issue/PRs in the other repo if you have any specific changes in mind. Thanks!
