### ISSUE TITLE
Buggy syntax highlighting

### ISSUE THREAD

**Issue by drguildo** [ionide/ionide-vscode-fsharp#1351]
A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/9282/80360425-3d59c300-8877-11ea-8572-bf092574c891.png)

Note how `match` and `Delay` look.

This doesn't seem to be confined to any particular theme and is a transient issue that comes and goes as I edit files.

**Environment:**
 - OS: Windows 10 1803
 - Ionide version: 4.9.0
 - VSCode version: 1.44.2
 - dotnet SDK version: 3.1.201

**Comment by drguildo** [comment]
On further inspection this looks like it might be confined to .fsx scripts. I also have a suspicion that it might be related to the code formatting as that feature seems to be completely broken for me within the context of F# projects but works for .fsx scripts.

**Comment by MangelMaxime** [comment]
Hello, 
the problem you are facing is that semantic highlighting is still coming from an older version of your file. It takes a bit of time to update the semantic highlighting because it needs to be retrieved from the F# compiler.

If you wait or re-save the file you should see the highlighting working. If you prefer to disable semantic highlighting and go back to "the old" way of highlighting the code you can use this setting:

```json
    "[fsharp]": {
        "editor.semanticHighlighting.enabled": false
    }
```

**Comment by drguildo** [comment]
Is that considered acceptable behaviour?

**Comment by MangelMaxime** [comment]
Well because it is not a bug per se but only the FCS being slow sometimes I would say yes.

We are not the one enabling the new `semanticHighlighting` support by default. It's VSCode which does that so that's VSCode expecting you so disable it or not depending on your preference.
