### ISSUE TITLE
100% CPU usage caused by FSharp.ProjectCrackerTools

### ISSUE THREAD

**Issue by blumu** [ionide/ionide-vscode-fsharp#152]
After running VSCode + Ionide for a while I start seeing an increasing number of instances of `FSharp.ProjectCrackerTools.exe` being created which slowly take over my machine to the point that I am having troubles right now opening this issue in GitHub. Sometimes it could be just a single instance of `FSharp.ProjectCrackerTools.exe` using itself 40% CPU.

![image](https://cloud.githubusercontent.com/assets/3913258/18229191/d7f558a2-7223-11e6-969e-67ed0d87c06f.png)

Version: Ionide-Fsharp 2.4.2
VSCode 1.4.0
OS: Windows 10 Anniversary update

**Comment by cloudRoutine** [comment]
We need more details about the context/conditions that are triggering all of these processes to spawn. Could you give us the simplest situation that causes this to occur?

**Comment by blumu** [comment]
@cloudRoutine I can't pinpoint the exact conditions triggering this. It just happens after using VSCode for some time (opening source files, switching git branches, ...). But in any case, since the project cracker tools is (for a reason that I don't quite understand) very CPU intensive, Ionide should not allow more than a fixed number of instances of the project cracker tool to run concurrently (this could be implemented using  semaphores for instance).

**Comment by matthid** [comment]
I can report something very similar (maybe the same). And its quite easy to reproduce.
Clone latest FAKE master and open Code on the root project folder. Now start editing files.
After some time CPU will be 100% by autocomplete processes spawning `dotnet` processes.

I guess ionide has problems with the number of netcore projects in this folder (src/app/) and just doesn't manage to analyse them all?

Let me know if you have problems reproducing this on FAKE master...

**Comment by czifro** [comment]
I have a similar issue. My project has multiple `fsproj`, 10 to be exact, under one `sln`. I have noticed the gradual degradation of performance with Ionide as my project grew with more `fsproj`. I have had instances where the process, called `mono-sgen32` would be using >140% CPU. In my case, though, there is only one process. I actually think that multiple processes would improve my situation.

**Comment by Krzysztof-Cieslak** [comment]
OK. I think that issue was caused by the fact that we were sending to FSAC `project` request whenever user opened new file, or edited file that was not yet parsed. Sending lot of `project` requests was not a problem usually - if the project was parsed, and the `fsproj` file wasn't changed then response was served from in-memory FSAC cache. Unfortunately problem was on the start of the plugin - sometimes project cracking takes a long time, and if user started to open new files, or edit some code just after opening editor we were sending lot of `project` requests (as always) but since first cracking there was no entry in in-memory cache, so such request was starting new instance of ProjectCracker (and hence flooding system with lot of processes and using lot of CPU).

This was fixed while we've reworked our startup strategy while implementing project explorer, and using `workspacePeek` FSAC command.

**Comment by Krzysztof-Cieslak** [comment]
As a side note, not really related to this issue, there are still some issues with FAKE repo - project parsing, and hence plugin startup, takes ages on this repository. I suspect that it's problem with @enricosada's utility for cracking SDK-based project files.
