### ISSUE TITLE
format  command would remove the width and type setting in string format

### ISSUE THREAD

**Issue by metasong** [ionide/ionide-vscode-fsharp#1540]
just past the following code into the fsharp file and run the alt+shift+f command:
```fsharp
let logName = $"""CGGC_{DateTime.Now:yyyy_MM_dd_HH_mm_ss_fff}"""
let msg = $"""{first,10:F}ms-{last,10:F}ms:: GCCGPause_in_{interval}ms -> count:{count, 8:D} sum:{sum, 8:F}ms per:{per,8:P1} av:{av, 8:F}ms min:{min, 8:F}ms max:{max, 8:F}ms {(if attention then "******" else "")}"""

```

**Comment by baronfel** [comment]
Thanks for submitting! This is because the version of fantomas we have bundled didn't have support for format specifiers like this. The latest preview version does, so we should look into updating.  I'll leave this open, but open another issue in fsautocomplete and link it, because FSAC is what will actually need to change.

**Comment by metasong** [comment]
thanks for the quick responds

**Comment by metasong** [comment]
but after I installed the fantmas-fmt extension and associate the alt+shift+f to it, I find it's the same result

**Comment by baronfel** [comment]
that could be the same root cause. I don't know who maintains that extension or what version of fantomas it's using, so it could also very well have the formatting issue, as this was only fixed relatively recently in fantomas.

**Comment by baronfel** [comment]
This has been pushed out in fsautocomplete 0.46.3.  this version can be used from current ionide if you:

* `dotnet tool install -g fsautocomplete --version 0.46.3`
* set the `"FSharp.fsac.netCoreDllPath"` setting to `"fsautocomplete"`, which causes Ionide to invoke `dotnet fsautocomplete` instead of it's built-in fsautocomplete.

**Comment by Krzysztof-Cieslak** [comment]
We have improved Fantomas integration since this was reported.
