### ISSUE TITLE
Spaces in parent folder file name bug

### ISSUE THREAD

**Issue by PaulFWatts** [ionide/ionide-vscode-fsharp#1565]
v5.7.1

### Describe the bug**
If there are spaces in the parent folder file name e.g. "07 Your first Fsharp Program" the Ionide build will fail, i.e. clicking on the green build arrow. However it works if pressing on the "bug" icon to build with debugging. Building and running at the CLI works find.

If there are no spaces e.g. "07_Your_first_Fsharp_Program" everything works fine.

### Screenshots

![image](https://user-images.githubusercontent.com/7057417/129285145-a28d6368-8501-4cb9-86cf-7838b1943191.png)

![image](https://user-images.githubusercontent.com/7057417/129285197-a0ee0e75-0042-4332-843d-b624da6e09c0.png)

Running on Windows Surface Laptop 3 with latest Windows 11 preview build.

Same problem with Windows 10 however MacOS does not have the problem.

**Comment by baronfel** [comment]
This is because of the [splitArgs](https://github.com/ionide/ionide-vscode-helpers/blob/master/src/Helpers.fs#L27-L45) from the ionide-vscode-helpers project, and more broadly any API that relies on splitting CLI args with spaces. That function is incorrectly splitting on the space in the file name and causing the issues you see.

Realistically, any CLI-spawning API should be taking an array of string arguments, so we'll need to refactor this entire set of related functions to fix this.

**Comment by Krzysztof-Cieslak** [comment]
So this should be fixed by the updates in Helpers package
