### ISSUE TITLE
v5.7.2 does not work

### ISSUE THREAD

**Issue by mrboring** [ionide/ionide-vscode-fsharp#1576]
### Describe the bug
v5.7.2 does not work in vscode. 

* No icon in side bar
* No intellisense
* No popup when mousing over a value
* Trying `Alt+Enter` gives `command 'fsi.SendSelection' not found`

I saw another user having the same issue in the `editor_support` Slack channel.

### Steps to reproduce
1. Open an existing `fsx` file.
2. Mouse pointer over a value does not show the popup.
3. Highlight some code and press `Alt+Enter`.

### Expected behaviour
* Icon in side bar
* Insellisense
* Popup when hovering over a value
* `Alt+Enter` should run the selected code in `FSI`

## Machine info
 - OS: Windows 10 10.0.19043 Build 19043
 - .NET SDK version: 5.0.400]
 - Ionide version: 5.7.2
 - VSCode version: 1.60.0 (user setup)

### Additional context
Reverting to v5.7.1 resolves the issue.

**Comment by forki** [comment]
yeah same here. 5.7.2 seems to be broken somehow /cc  @baronfel @Krzysztof-Cieslak

**Comment by alfonsogarciacaro** [comment]
At least it's not only me, I thought I messed too much with these extensions and was crazy removing and reinstalling VS Code. @Krzysztof-Cieslak says here the update is working for him 😕 https://github.com/fsharp/FsAutoComplete/pull/830#issuecomment-916771216

Weird thing is the VS Code logs don't say anything.

![image](https://user-images.githubusercontent.com/8275461/132844658-210d225f-cb12-4e98-96cc-05ebed200d11.png)

I tried by adding a `debugger` to the "activate" function of Ionide and running an Extension host and did get some errors about missing modules (like "Cannot find module bufferutil") although the stack didn't include Ionide code so not entirely sure if the errors were caused by it. Can it happen that in some machines these missing modules are installed globally and that's why the update works?

**Comment by shazmodan** [comment]
I have the same problem. **Reverting to 5.7.1** still works however.

**Comment by alfonsogarciacaro** [comment]
Now properly debugging after building this repo. Still not sure what the problem is, but it seems the extension hangs when trying to run `cmd /C where dotnet.exe` to find the path of dotnet in windows. The "exit" event in the spawned process is never called (nor "close" apparently).

**Comment by baronfel** [comment]
Thanks, this is probably a result of some typing definition updates that came along with the FSAC update. I'll work on rolling those back early this morning and releasing a new version. Gotta get some coffee first though!

**Comment by alfonsogarciacaro** [comment]
Just the change from #1579 makes 5.7.2 work on my computer. Now you ask me why it was working before... I have no idea.

As an aside, in this helper the `options` set at the top are not being

**Comment by baronfel** [comment]
5.7.3 is rolling out now, and @alfonsogarciacaro I've also made the suggested fix to the helpers - thanks for that spot!

**Comment by forki** [comment]
I can confirm. It's fixed for me. Thanks folks

**Comment by mrboring** [comment]
v5.7.3 is working fine for me. Thanks for the quick response!

**Comment by akemimadoka** [comment]
v5.7.3 still not working on Ubuntu for me, should I open another issue?
