### ISSUE TITLE
Provide default settings for VSCode Explorer File Nesting feature

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1724]
VSCode 1.67 provides a new File Nesting feature: [docs](https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting)

We should provide default `explorer.fileNesting.patterns` for F# files, so that when users turn the feature on via `explorer.fileNesting.enabled` F# just works.

Proposed mappings:

```json
{
  "contributes": {
    "configurationDefaults": {
      "[fsharp]": {
        "explorer.fileNesting.patterns": {
          "*.fs": "${basename}.fsi, ${basename}.fs.js, ${basename}.fs.js.map",
          "*.fsl": "${basename}.fsi, ${basename}.fs",
          "*.fsy": "${basename}.fsi, ${basename}.fs"
        }
      }
    }
  }
}
```

**Comment by baronfel** [comment]
@jasiozet would you be interested in contributing the feature? it would involve adding the above to `release/package.json` in the existing `contributes` section, then testing that the folding works as expected.

**Comment by jasiozet** [comment]
![image](https://user-images.githubusercontent.com/18668118/177035487-04508ade-4daf-45ee-b6a4-ff3c3eccccd9.png)
I think it needs to be in the main scope (not the language scope)
But the problem is if it is in multiple file types it doesn't work properly:
![image](https://user-images.githubusercontent.com/18668118/177035719-f361bf00-418d-4c9b-a5a2-30fcfa177ad3.png)
```
"explorer.fileNesting.patterns": {
    "*.xy": "${basename}.xy, ${basename}.xy.z, ${basename}.xy.j",
  }
```
Produces this:
![image](https://user-images.githubusercontent.com/18668118/177035789-ec75ec37-531f-4c00-85de-ed7b93dad34f.png)
and this:
![image](https://user-images.githubusercontent.com/18668118/177035743-e8b30140-00e8-4c9d-9057-5a5d43a5ff3a.png)
From my testing the last section is properly evaluated. I am not sure how to test this with contributes, maybe this will behave correctly and they would be evaluated into 1 section?

Also worth considering:
```
"explorer.fileNesting.enabled": true,
```
This also need to be enabled on global level, not language level.
