### ISSUE TITLE
Mixed F# with C# solution shows completly wrong in solution explorer

### ISSUE THREAD

**Issue by jkone27** [ionide/ionide-vscode-fsharp#1757]
### Describe the bug
I expect only F# code to show up in solution explorer, instead C# code is shown and F# code is not

### Steps to reproduce
Create a project with F# unit tests, referencing a C# console project.

Open it in ionide

### Expected behaviour
F# solution explorer loads F# files, but leaves out C# files? It's confusing

### Screenshots
<img width="450" alt="image" src="https://user-images.githubusercontent.com/10419217/182836476-13050143-873f-4d56-9244-8525692c57a6.png">

<img width="425" alt="image" src="https://user-images.githubusercontent.com/10419217/182836561-47a270e0-e762-4447-a05f-790756e819e4.png">

## Machine info
 - OS: MAC
 - .NET SDK version: 6.0
 - Ionide version: 7.0.0

**Comment by Krzysztof-Cieslak** [comment]
> F# solution explorer loads F# files, but leaves out C# files? It's confusing

Well, it is called **F#** solution explorer ;-) 

But yeah, better support for `csproj` files is something I wanted to do for a while.

**Comment by MangelMaxime** [comment]
Tested with Ionide 7.0.0:

I wanted to have a look at this issue but I am not sure what the problem is.

File explorer:

![image](https://user-images.githubusercontent.com/4760796/184887650-fe72038f-00dc-4e02-8edc-367db804e9f8.png)

F# solution explorer:

![image](https://user-images.githubusercontent.com/4760796/184888147-68585424-b45d-437d-85bc-6023aadd7354.png)

It looks like both F# and C# project are loaded and displayed with their respective files.

The difference between F# and C#, is that F# project don't have the `.fsproj` suffix and the `obj` folder is hidden.

From this observation, I suppose we can remove the differences. But I don't really see a bug.
