### ISSUE TITLE
Reference codelense not shown if the function/variable is a single letter

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1763]
### Describe the bug

![image](https://user-images.githubusercontent.com/4760796/184987884-37591450-1034-47ed-95fe-1f607427520a.png)

```fs
let y () = "" // This line doesn't have the references count shown

let yy () = ""

let add () = ""
```

## Machine info
 - OS: Windows
 - .NET SDK version: [e.g. 5.0.100]
 - Ionide version: 7.0.0

**Comment by Krzysztof-Cieslak** [comment]
This is true for all single character identifiers - probably some off by one error somewhere in FSAC:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/5427083/184990824-a73451c0-1c34-415f-8e06-d61693765c4c.png">

**Comment by baronfel** [comment]
This isn't an off-by-one actually! We actually get a NavigationItem back from the compiler for these single-character identifiers:
![image](https://user-images.githubusercontent.com/573979/185155393-c3ea3326-86dc-4c81-8b84-c52927d7d542.png)

The problem is that we map out `Field` type glyphs in the codelens mapping:

```fsharp
|> Array.filter (fun n ->
      not (
        n.Glyph <> FSharpGlyph.Method
        && n.Glyph <> FSharpGlyph.OverridenMethod
        && n.Glyph <> FSharpGlyph.ExtensionMethod
        && n.Glyph <> FSharpGlyph.Field
        && n.Glyph <> FSharpGlyph.EnumMember
        && n.Glyph <> FSharpGlyph.Property
        || n.IsAbstract
        || n.EnclosingEntityKind = NavigationEntityKind.Interface
        || n.EnclosingEntityKind = NavigationEntityKind.Record
        || n.EnclosingEntityKind = NavigationEntityKind.Union
        || n.EnclosingEntityKind = NavigationEntityKind.Enum
        || n.EnclosingEntityKind = NavigationEntityKind.Exception
      ))
```

We could consider removing this - it seems that some functions are either mistagged as Fields or are purposefully compiled as such.
