### ISSUE TITLE
Vs Code no longer detects F# Projects and is unable to debug

### ISSUE THREAD

**Issue by parkeradam** [ionide/ionide-vscode-fsharp#1870]
Steps to reproduce:
1) Create a new F# console 
2) Open in Vs Code with Ionide enabled. 
3) Hit F5 to try and run the proejct. 

Expected Behaviour : The project is able to be selected to run and debug using dotnet core
Actual Behavior: The extension is unable to figure out what the project is and as such is unable to debug in this way. 

![image](https://user-images.githubusercontent.com/30392071/235492834-0421ee5d-6d65-4674-ac7e-1ab2586f3aa2.png)

If the Ionide Extension is disabled, the dotnet core debugger option re-appears
![image](https://user-images.githubusercontent.com/30392071/235493254-f0e613c3-4902-4b39-b168-4ee9103a8227.png)

If you use the "Run" button in the Ionide/F# side panel it works but not for F5.

Machine Specifications: Windows 10
Ionide Version : 7.5.3

This has been dicssed here : https://github.com/ionide/ionide-vscode-fsharp/discussions/1827#discussioncomment-5771998

If any further information is required I will be happy to provide.

**Comment by baronfel** [comment]
I _think_ the problem is [here](https://github.com/ionide/ionide-vscode-fsharp/blob/09ea8c08afe27a96f45c94178ac51e1b38739f1d/release/package.json#L832) and [here](https://github.com/ionide/ionide-vscode-fsharp/blob/09ea8c08afe27a96f45c94178ac51e1b38739f1d/src/Components/Debugger.fs#L404C22-L409) where we override the `coreclr` debug type. We probably need to choose a different identifier for these two places, but leave the `coreclr` `type` on the launch configurations our provider generates - so that we use the C#-provided configuration.

**Comment by shishini** [comment]
i would like to share my experience, because i too was faced with the same issue
note that i was following a simple tutorial to run and debug F# from vs code 

so because of this issue i was unable to create the files
1.launch,json
2. tasks.json 

now, i would like to highlight some concern as someone who dont code often (using general purpose languages)
1. those too files , their use and their creation while seemingly very important, are not documented on the ionide site
instead there a link to generic vs code documentation on MS Siste 
[ionide site](https://ionide.io/Editors/Code/running.html) , [ms site](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations)
2. As I was clicking around trying to make sense of what happened, I got a warning about Omnisharp not starting, again, no easy way to find how this related to ionide and fsharp
3. I found this issue while googling https://github.com/ionide/ionide-vscode-fsharp/issues/1689 , so it seems that this area and problems with this area seem to be recurring 
4. running `Debug: Select and Start Debugger` seem to enable debugging in vscode without the need of launch.json and tasks.json , so now I dont know what they are needed at all, and why they are not fully automatically created (in the background and transparently, if truly needed) 

In general. the overall experience , the available documentation, the issue history, turned this into a very intimidating experience , and I just wanted to share that

**Comment by baronfel** [comment]
Thanks for the feedback, everyone. I've got a PR open that will fix this, but VSCode also has some behaviors here that aren't the greatest. In an open workspace, when no other debug/launch target has been selected before, pressing F5 runs an 'empty' launch configuration. This is not ideal. I've asked in #1871 if we (Ionide) should consider 'hijacking' this empty configuration if the currently selected file or project when F5 was pressed was an F# project we know about, but I'm very wary here of being too aggressive.  In the meantime, please check the gif in #1871 for an example of our out-of-the-box debugging support once this lands and is released. We'll try to work on docs as well, but we would also love any contributions you might have here! The docs are all open-source and can be found at https://github.com/ionide/ionide.github.io.

**Comment by shishini** [comment]
Hi I wanted to add i posted this issue on the omnisharp page/repo [omnisharp-vscode/issues/567](https://github.com/OmniSharp/omnisharp-vscode/issues/5677)

I am not sure if this is an ominsharp bug or an ionide bug
but i still get this error even after the latest update
I think this issue is but tricky, this it seem to be environment dependent,
So I think not all users will get it

**Comment by parkeradam** [comment]
Thank you @baronfel , I've updated and seems to be working for me now. Very much appreciate it :)

**Comment by shishini** [comment]
Its not working for me

F5 or Ctrl+F5 do nothing 
I think its because of the  "Cannot create .NET debug configurations. The OmniSharp server is still initializing or has exited unexpectedly." error

But to get to that, since F5 or Ctrl+F5 do nothing 
I go the the debug menu 

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/2177439/2d10a154-1fb6-4d2a-96c0-c91f4ef62238)

click create a launch,json file and select .net core from the command bar on top 

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/2177439/4ac9cc3f-69fa-48d4-bb89-79eafc733ed6)

**Comment by shishini** [comment]
Few more things, the latest update still fixed few things, so maybe the Omnisharp server issue is not directly related 
But now when I click F5 or Ctrl+F5 i dot get prompt for the debugger and the menu have the .net option, before it did not 
but when i choose it nothing happen, the launch.json file is not created
![image](https://github.com/ionide/ionide-vscode-fsharp/assets/2177439/ea73c375-864e-47df-80e9-ec255299cff2)


When I user the debugger menu,  and select the create launch,json file the json file is created , but I get the omnisharp server error 

Next what I do is I closed the file , and reopened it again
Now i can see the add configuration button at the bottom

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/2177439/84cff5c3-f08c-44f7-9a1e-dd332d81486e)


And from that point things seem to work as expected
