### ISSUE TITLE
Text moving up screen because code lenses function signatures disappear

### ISSUE THREAD

**Issue by mrboring** [ionide/ionide-vscode-fsharp#1891]
### Describe the bug

Quite often when I'm typing all the code lenses function signatures disappear then reappear a few seconds later. In long code files this causes the text to move up the screen. This happens many times per day.

I've attached animated gifs. One for a small file and another for a large file.

I also noticed there were 343 uncaught errors for the Ionide extension:

```
Count Name
----- ----
   61 Cannot find ident for tooltip
  259 Illegal argument: line must be non-negative
    1 No line in c:\Data\test.fsx at position (1,0)
    1 No line in c:\Data\test.fsx at position (3,0)
    1 No line in c:\Data\test.fsx at position (3,11)
    1 No line in c:\Data\test.fsx at position (3,12)
    1 No line in c:\Data\test.fsx at position (3,4)
    1 No line in c:\Data\test.fsx at position (3,6)
    1 No line in c:\Data\test.fsx at position (3,7)
    1 No line in c:\Data\test.fsx at position (3,9)
    1 No line in c:\Data\test.fsx at position (4,0)
    1 No line in c:\Data\test.fsx at position (5,0)
    1 No line in c:\Data\test.fsx at position (6,0)
    1 No line in c:\Users\<removed>|AppData\Local\Programs\Microsoft VS Code\Untitled-1.fsx at position (1,0)
    8 No tooltip information
    3 System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

### Steps to reproduce
1. Create an `fsx` file.
2. Create a number of functions.
3. Near the bottom of the file (this will show the code movement more) start typing some text. I found that sometimes I needed to press return at the end and other times I did not.

### Expected behaviour
The code should not jump up the screen.

### Screenshots
A single `fsx` file:
![Small file](https://github.com/ionide/ionide-vscode-fsharp/assets/5991977/b587c603-24d1-435d-92af-f0b034fd74a2)

An `fsx` inside a folder containing other `fsx` files:
![Bigger file](https://github.com/ionide/ionide-vscode-fsharp/assets/5991977/3a5964fd-60bf-4e25-8593-d85aae21a095)

## Machine info
 - OS: Windows 10 Pro 22H2 (OS Build 19045.3086)
 - .NET SDK version: 7.0.302
 - Ionide version: 7.7.0

**Comment by baronfel** [comment]
This behavior is likely something we can't directly fix in Ionide, but I expect it to be fixed automatically in a future version of Ionide when we get a newer version of the Fsharp Compiler Service that contains fixes to the parser recovery. That likely won't happen until the November release of .Net 8.

**Comment by mrboring** [comment]
I have a second PC on which I sync the extensions and settings. I've checked and the settings are the same. Also the verions of: Windows, .NET SDK and Ionide. On this second PC I can't recreate the issue! Can you suggest anthing else to check?

**Comment by baronfel** [comment]
No - there's likely nothing you can do here by tweaking VSCode settings alone. What's happening here is (likely, this is speculation based on my knowledge of the compiler APIs):

* new line is entered
* parser doesn't 'recover' nicely in this case, and fails parsing
* F# Compiler Service APIs report no type information _briefly_, which means no lenses (since those are powered by typecheck information)
* We basically act as a pass-through sending the FCS data directly to VSCode
* Shortly after, the parser/typechecker catches up, so there is typecheck data
* We pass that new data along

Some of the work that's been done over the past month in dotnet/fsharp is drastically improving the 'recover' mechanisms in areas of the parser, which means this flickering should be much less likely.  We in FSAC/Ionide will try to pull those in on the nightly builds of FSAC and check out the user experience, but those changes likely won't release until November along with the rest of .NET 8.

It's _possible_ that we could try and do some buffering/debouncing in FSAC to help skip over this kind of experience, but it would take an unknown amount of time to investigate and see if we _could_ control this.

**Comment by TheAngryByrd** [comment]
We may be able to store a last “good” (no diagnostics) typecheck and use that but at the cost of another cache. But yeah it’s exploratory at this point.

**Comment by mrboring** [comment]
My second PC has an i5-9500T (6 cores) and my main PC has an i7-7820HQ (4 cores and hyper-threading). Though it's an i5, it's a newer model, so maybe it's a bit quicker.

I searched and couldn't find any other people having the same issue. So I don't think it's worth spending time on, unless you have nothing else to do.

**Comment by TheAngryByrd** [comment]
I’ve definitely experienced it but I generally turn them off for performance reasons.

**Comment by mrboring** [comment]
It's good to know someone else has had the issue. I think I'll turn them off also.

FWIW, here is a summary of the errors from my second PC:

```
Count Name
----- ----
   61 Cannot find ident for tooltip
 5217 Illegal argument: line must be non-negative
    1 No line in c:\Data\Untitled-1.fsx at position (42,0)
   15 No tooltip information
    2 System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

**Comment by TheAngryByrd** [comment]
I also looked around and seems like this is an issue in VSCode as many other plugins have problems with codelens

- https://github.com/microsoft/vscode/issues/26166 
- https://github.com/microsoft/vscode/issues/27074
- https://github.com/microsoft/vscode/issues/32877
- https://github.com/microsoft/vscode/issues/18474
- https://github.com/microsoft/vscode-python/issues/14029 (they even moved away from codelens because of the experience)

I really doubt we'll be able to do anything here :(

**Comment by mrboring** [comment]
Thanks for looking into this. I've disabled the lenses for F# and haven't really missed them.
