### ISSUE TITLE
Fsproj Highlighting doesn't work anymore

### ISSUE THREAD

**Issue by tforkmann** [ionide/ionide-vscode-fsharp#1905]
### Describe the bug
FSproj file won't get highlighted anymore

### Steps to reproduce
Install lastest ionide version
Got to any fsproj file

### Expected behaviour
Correct Highlighting of the fsproj file. Last working version 7.7.0

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/4168951/0a625661-c011-49bb-95c2-88b702619868)

### Screenshots
![image](https://github.com/ionide/ionide-vscode-fsharp/assets/4168951/6e648526-d98e-4c23-a493-c3f66f0a4265)

## Machine info
 - OS:Mac/
 - .NET SDK version: [7.0.306]
 - Ionide version: [7.8.5]

**Comment by baronfel** [comment]
In that version we switched the 'language' of MSBuild files to `msbuild` instead of letting VSCode infer it as `xml` - there's an extension for MSBuild files called [MSBuild Project Tools](https://marketplace.visualstudio.com/items?itemName=tintoy.msbuild-project-tools) that I very much recommend you install - that will bring syntax highlighting back.

If you prefer not to, you can tell VSCode to override them to xml:

```
"files.associations": {
	"*.fsproj": "xml"
}
```

put that in any VSCode settings json and you should be good to go.

**Comment by tforkmann** [comment]
@baronfel Thank you that works!
