### ISSUE TITLE
Read ~/.bashrc When Running A .fsx Script?

### ISSUE THREAD

**Issue by eatobin** [ionide/ionide-vscode-fsharp#1983]
Hello -

Is there a way to have your `~/.bashrc` read when running a `.fsx` script? I'm trying to set my terminal prompt correctly and I've included a screenshot of the current output - which I'd like to change to reflect my PS1.

Thank you!

![prompt](https://github.com/ionide/ionide-vscode-fsharp/assets/870698/5a407716-fe4f-4b85-91d6-a874eb6e7e17)

**Comment by MangelMaxime** [comment]
To me it looks like there is a mix happening here. Because, you are trying to setup a Powershell configuration from inside a `.bashrc` which is in general associated to `bash` and not Powershell.

I think customisation of Powershell should be done inside the `$PROFILE` code. 

Exemple: `notepad $PROFILE`

https://learn.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup#choose-and-apply-a-powershell-prompt-theme

**Comment by eatobin** [comment]
@MangelMaxime Thank you - but I don't understand. Where does Powershell come in? I am on Linux (Ubuntu) and use `bash`. Is Powershell used by Ionide-VSCode to run a `.fsx` script?

**Comment by MangelMaxime** [comment]
Oops sorry I thought `PS1` was related to PowerShell as when quickly looking at the screenshot I thought that the window I took for a window terminal (Sublime Text) looked similar to Windows Terminal.

I was probably not properly awake this morning 😅

**Comment by eatobin** [comment]
No problem. Any thoughts on how to read the .bashrc file before running a
.fsx in ionide?

**Comment by MangelMaxime** [comment]
We don't spawn the terminal ourself, it is given to use by VSCode API.

https://github.com/ionide/ionide-vscode-fsharp/blob/29205de7dd1467a21210a9d18a20b79e4b34d752/src/Components/Fsi.fs#L419-L455

I don't know if there any arguments or configuration can be made for it.

**Comment by eatobin** [comment]
@MangelMaxime Thank you. I'll just live with it. :-)

**Comment by eatobin** [comment]
Bye.
