### ISSUE TITLE
Some features not working on OSX

### ISSUE THREAD

**Issue by latkin** [ionide/ionide-vscode-fsharp#26]
I'm on VS Code 0.10.3 on OSX.  Some features of the extension *do* work:

 - Intellisense
 - Quickinfo

But other features do *not* work:

- Syntax highlighting
- Any kind of commands, e.g. fsi (or at least I can't find them?)
- No settings exposed

Given that non-trivial stuff like intellisense is working, clearly the install was "successful," but maybe some config to wire up other stuff is missing?  Is there a log I can look at or tips on how to debug? Or maybe these features are simply not yet supported on OSX?

**Comment by Krzysztof-Cieslak** [comment]
That's actually really surprising - usually people complains that "complex" stuff is not working ;)

Every feature is supported on all platforms. To be fair, I would suggest reinstalling plugin - it might be some installation problem.

**Comment by Krizzzn** [comment]
I think I found out what the issue is.

Since El Capitan `mono` and `fsharpi` are not placed in `/usr/bin/` but in `/usr/local/bin/`. If you change the pathes in the package setup accordingly it works like a charm.

My issue is that I'm unable to change these pathes when using fsharp in Visual Studio Code. I couldn't find out how to configure the paths in VSC. And VSC does not offer a package configuration similar to Atom. (Any hints?)

Hope this helps @Krzysztof-Cieslak in finding the issue.

**Comment by naveensrinivasan** [comment]
I agree. I am also facing the same issue where I can't `mono` and `fsharpi` path.

**Comment by epeicher** [comment]
Same issue here with Yosemite

**Comment by danslapman** [comment]
Same on El Capitan

**Comment by Krzysztof-Cieslak** [comment]
Visual Studio Code has access to `PATH` on OSX (what is unfixed bug in Atom) and should just work if `mono` and `fsharpi` are in `PATH`

**Comment by danslapman** [comment]
After mono reinstallation it works... Mystic!
