### ISSUE TITLE
Minor format change in fsproj, potential bug

### ISSUE THREAD

**Issue by czifro** [ionide/ionide-vscode-fsharp#341]
I have noticed that the fsproj has changed format slightly in this [pull request](https://github.com/dotnet/cli/pull/5244).  It appears that `ToolsVersion="15.0"` has been dropped. This directly affects FSAC, [here](https://github.com/ionide/FsAutoComplete/blob/master/src/FsAutoComplete.Core/Commands.fs#L111). For those who are using `rc4` and create a new project, this is an issue. The symptoms are that autocomplete will fail to recognize referenced packages. I have done a little searching through issues on this repo and have not seen this popup yet (maybe on a different repo?). Since it appears to be a simple fix, I would be willing to fix this, unless someone else is already doing so.

**Comment by czifro** [comment]
I can produce this. Steps to produce:

1. `dotnet new -l=fsharp -t=xunittest`
2. `dotnet restore && dotnet build`
3. `code .` // open folder in vscode

Test environment:

```
OS => macOS Sierra
DotNet Version => 1.0.0-rc4-004530
```

I used `xunittest` since it has package references and that was the initial reason for [this pr](https://github.com/ionide/FsAutoComplete/pull/30), which started with [this issue](https://github.com/xunit/xunit/issues/859) (towards bottom). @enricosada should be familiar with this issue.

**Comment by enricosada** [comment]
@czifro the fix is minimal, but cannot do that atm. Code to be changed is [there](https://github.com/enricosada/FsAutoComplete/blob/98c1e3634d892c8522a4cc030b1bbf834ffa1ec4/src/FsAutoComplete.Core/Commands.fs#L97-L123)

Basically there is a function who decide if is the new msbuild format or not, atm just check ToolVersion.
I think can be changed like:

If exists `Sdk` attribute

Just checking the Src attribute is ok, because preview3 (the only one with toolversion=15 and no Sdk attribute) is obsolete and not used.

For sdk attribute i mean the one in `<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk"``

**Comment by czifro** [comment]
@enricosada, I have written the fix, but have not committed it. I'll just commit and do a pr. It is precisely as you have outlined.
