### ISSUE TITLE
New project: forge looks for build.sh in the wrong place

### ISSUE THREAD

**Issue by Martin521** [ionide/ionide-vscode-fsharp#462]
Forge output:
Unhandled error:
Could not find file 'd:\Test2\src\build.sh'.

While build.sh sits in d:\Test2

**Comment by Krzysztof-Cieslak** [comment]
This is fixed in upcoming Forge 2.0 - https://github.com/fsharp-editing/Forge/pull/71

**Comment by rmunn** [comment]
Just encountered this one myself, running Ionide-fsharp version 2.28.0 in VS Code 1.14.2. Might I suggest that this issue stay open until Forge 2.0 is available in Ionide? I almost created a duplicate issue to re-report this -- and since it is a current bug in Ionide, even if it's a known bug, I'd suggest keeping an Ionide issue open until the fix is actually released.
