### ISSUE TITLE
erroneous linter warning in F# 4.1: This number is outside the allowable range for 32-bit signed integers

### ISSUE THREAD

**Issue by s952163** [ionide/ionide-vscode-fsharp#463]
The linter incorrectly reports an error for numeric literals separated by `_`, e.g. `100_1000`. The compiler itself correctly identifies the type and ionide will compile this without errors. Rider or VS2017 do not show this warning unless the literal is truly out of range. In the screenshot other 4.1 types, like `Result` are working fine. 

<img width="667" alt="fsharp41err" src="https://user-images.githubusercontent.com/16188516/27858434-2c551bfe-61b0-11e7-8d9a-06f3bd715aea.PNG">

**Comment by enricosada** [comment]
@s952163 this is because the F# language server (powered by [fsharp/FsAutoComplete](https://github.com/fsharp/FsAutoComplete)) use an older version of [fsharp/FSharp.Compiler.Service](https://github.com/fsharp/FSharp.Compiler.Service/)

is tracked by https://github.com/fsharp/FsAutoComplete/issues/183

closing this. wil be fixed after referenced issue is closed

**Comment by s952163** [comment]
Much appreciated! I thought it would be hiding somewhere in FSAC just but wasn't sure why the others didnt show the same behavior.
