### ISSUE TITLE
MSBuild commands do not work if no code file is opened in the editor

### ISSUE THREAD

**Issue by luminescent** [ionide/ionide-vscode-fsharp#465]
Steps to reproduce:

- open an FSharp project in Visual Studio Code (I had one based on .NET Core) 
- close all of the editor windows with code in them (best to close all windows)
- invoke MSBuild: Build Current Project 

This will produce a series of errors like the one in the attached screenshot:
![image](https://user-images.githubusercontent.com/1205646/28173745-46712d6a-67e7-11e7-9d20-53e8f243023b.png)

Current workaround: open a `.fs` file in the editor and try the commands again, this time they will work.

**Comment by Krzysztof-Cieslak** [comment]
I think that the problem is bit more complex than expected. There are couple of problems here (and all those points applies also to Expecto commands since there are fairly similar in the design).

1. MsBuild commands are not added to "activation" events, what means that Code returns this "command XYZ not found" error message when user tries to use them before plugin is activated. 
2. Even if they were added they still won't work well - they depend on plugin being in "fully initialized" state, which takes a while (it requires full parsing of all projects in workspace)

Probably the right solution will be:
1. Add them to activation events (or maybe use "workspace contains" activation event)
2. Print out nice information messages that the plugin needs to be fully initialized when user tries to  use those commands before the plugin is fully initialized.

**Comment by Krzysztof-Cieslak** [comment]
`2.28.0` changed startup strategy, so now it should work.
