### ISSUE TITLE
Feature request: support Underscores in Numeric Literals for syntax checking on *.fs and *.fsx

### ISSUE THREAD

**Issue by pronetag** [ionide/ionide-vscode-fsharp#482]
Based on [MSDN from F# 4.1](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/literals), underscores in numeric literals are supported like below:

`let ssn = 123_456_7890`

However, with ionide-vscode-fsharp, it will prompt an error in Visual Studio Code editor that 

> "This number is outside the allowable range for 32-bit signed integers".

![issuescreenshot_supportunderscoresinnumericliterals](https://user-images.githubusercontent.com/3295084/29000264-6164f05c-7a98-11e7-849b-5074e11dcffb.PNG)

Actually this statement works when I use Alt+Enter to send it to F# Interactive. 

![issuescreenshot2](https://user-images.githubusercontent.com/3295084/29000296-fbcaefac-7a98-11e7-977e-b5350f1364b4.PNG)

Then I guess only syntax checking is not updated for this new language feature from F# 4.1.

Please add the support Underscores in Numeric Literals for syntax checking. Thanks!

**Comment by Nemeczek** [comment]
If I understand correctly this issue is related to [FsAutoComplete](https://github.com/fsharp/FsAutoComplete). Which is the backend for Ionide. (which calls underlying [FCS](https://github.com/fsharp/FSharp.Compiler.Service). 

Update:
And the same issue was already raised [here](https://github.com/ionide/ionide-vscode-fsharp/issues/463)

**Comment by pronetag** [comment]
thanks and waiting for the fix.
