### ISSUE TITLE
It does not use msbuild from mono, but dotnet msbuild

### ISSUE THREAD

**Issue by kkpoon** [ionide/ionide-vscode-fsharp#611]
OS: Mac

I have `mono`(installed from Visual Studio for Mac) and  `dotnet-cli` co-exist in my macOS. My project required to use .NET framework 461. When I open vscode, the F# Project explorer always marks my .fsproject **(load failed)**. It also build failed when I use Command "MSBuild: Build Project". Then I run Command "MSBuild: Switch host type" to use mono msbuild, output:
```
MSBuild (.NET) activated
```

It built success

However, no matter what I have selected, the Project Explorer, on the left hand side, still using `dotnet msbuild` to build my project, with the result "(load failed)".

Error
```
Error:
MSBuild failed with exitCode 1 Working Directory: 'somewhere' Exe Path: 'dotnet' Args: 'msbuild somewhere/someproject.fsproj ....'
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    ...
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>
```

I tried to add the following to my workspace setting `.vscode/settings.json`
```json
{
    "FSharp.msbuildHost": ".net"
}
```
no effect to the Project Explorer (load failed), but good at Command "MSBuild: Build Project".

Thanks

**Comment by enricosada** [comment]
Hi @kkpoon 

Atm this is a limitation of the FSAC (the language service) who parse the fsproj, who use `dotnet` executable (running `dotnet msbuild`)

The parsing fails, because dotnet cli doesnt known where the mono references assemblies are (see below), so `dotnet build` will fail, and project parsing too.

the `FSharp.msbuildHost` setting is used only to choose what use when you do `Build` like commands, not yet for project parsing

As workaround, dotnet cli can  build projects targeting .net (llike `net461`), you just need to know where reference assemblies are (the assemblies of .net framework 4.6.1 installed in mono).
Yo can use this workaround https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0#using-net-framework-as-targets-framework-the-osxunix-build-fails
You can add that for your user, so will work opening new terminal and code
After that, doing `dotnet build` will work from command line too, and project parsing will work correctly in code

Closing because is tracked in https://github.com/fsharp/FsAutoComplete/issues/213 and there is a workaround

@kkpoon any issue with workaround, feel free to reopen this.
