### ISSUE TITLE
make syntax highlighting distinguish between values and functions

### ISSUE THREAD

**Issue by detachmode** [ionide/ionide-vscode-fsharp#621]
It would make reading code easier in my opinion, if the colors are different for values and functions.

``` fsharp
let x = 1
let increment v = v+1

let result = increment x  // increment should have a different color than x

```

**Comment by Krzysztof-Cieslak** [comment]
Due to the fact that VSCode highlighting is driven by a bunch of RegExes and how complex actual F# grammar is, I don't think we can do anything about it at the moment. 

There is issue on VSCode repo about adding API for semantic highlighting, it would allow us to do more accurate syntax highlighting (like in VS and Rider)
