### ISSUE TITLE
Outdent moves cursor to beginning of line instead of previous tab stop

### ISSUE THREAD

**Issue by chadunit** [ionide/ionide-vscode-fsharp#641]
When working on F# files in VS Code + Ionide, using Shift-Tab or Ctrl-[ to outdent moves the cursor to the beginning of the line, instead of just backing up one tab stop.

This only happens in F# files. In C#, Javascript, and JSON files (didn't test any others), the outdent works as expected and only moves one tab stop at a time. It also works as expected in F# files after disabling the Ionide-fsharp extension.

**Simple repro:**

1. Create a .fs file with the following code:

```
let main args =
    let test () =
        printfn "a"
```

2. Press Enter after the printfn line, cursor will be positioned below the p.

3. Press an outdent shortcut key, Shift-Tab or Ctrl-[.

**Expectation:**

Cursor should be on the first tab stop, aligned with the "let test" line.

**Actual:**

Cursor goes to beginning of line.

This is with Ionide-fsharp v3.12.2.

**Comment by inosik** [comment]
I think this is rather a "bug" in VS Code, because that happens in Yaml files too, when you add this to your configuration:

``` json
"[yaml]": {
  "editor.useTabStops": false
}
```

This is what gets set by Ionide by default, to allow us to indent things like the following snippet correctly:

``` fsharp
let pt =
  { x = 0
    y = 0 } // <- This is the problematic line
```

But somehow the VS Code guys achieve the same thing for Yaml _without_ adding anything to the configuration. I looked through the default Yaml extension but couldn't find anything.

**Comment by Krzysztof-Cieslak** [comment]
@inosik, Yaml extension is using 2-spaces indent by default which solves the problem of such code as
```
let pt =
  { x = 0
    y = 0 }
```
Unfortunately, we can't do this in F# since both 2 and 4 spaces are widely used by Community.

**Comment by inosik** [comment]
> Yaml extension is using 2-spaces indent by default

That makes sense, I didn't think about this.

**Comment by chadunit** [comment]
Interesting, thank you. I see there is an fsharp override for that setting which explains the isolated behavior.

I have set useTabStops = true for fsharp and I believe this resolves the issue for me, as I tend not to use column alignment and will prefer to use the improved cursor outdent behavior.

**Comment by kspeakman** [comment]
This has been driving me crazy.

At first, I wasn't bothered by shift-tab going to the beginning of the line. I would just tab back to the place I wanted to be without thinking about it. However, when it move to the beginning of the line, it leaves most of the whitespace on the right of the cursor.

```fsharp
            // cursor here, 3 tabs of white space to left
            |
// after shift-tab, cursor at beginning, two tabs of whitespace to the right
|       _
```

I only started noticing that many of my lines have a bunch of whitespace on the end. When I would hit End, the cursor would go 12 spaces past the end of line. Argh.

I would expect it to remove all whitespace if it moves to the beginning. Is this a VS Code or Ionide thing?

**Comment by inosik** [comment]
That‘s certainly VS Code, it‘s reproducible without any extensions. I created Microsoft/vscode#42041 some weeks ago.

**Comment by kspeakman** [comment]
Awesome, thank you for filing that! For now I will re-enable tab stops.

**Comment by stevenybw** [comment]
After two years, exactly the same problem arises again with the newest Ionide and VSCode. It is really annoying. Any solution to this issue?

Iodine version: 4.6.0
VSCode version: 1.42.1

**Comment by inosik** [comment]
Unfortunately, no. This isn't an issue with Ionide, though. See the linked issue in [my comment](https://github.com/ionide/ionide-vscode-fsharp/issues/641#issuecomment-366015731) above.

**Comment by stevenybw** [comment]
Glad to see your fast response @inosik. 

I'm not sure if there is any technical obstacle from the correct cursor outdent behavior of Ionide.  However, I think it is with high probabilities that it is the issue from Ionide because I have tried some other plugins and their behavior is expected:
C/C++ 0.26.3
C# 1.21.12
Scala (Metals) 1.7.8

Outdenting issue is important because we have to indent and outdent very frequently because F# scope is based on indent.

**Comment by inosik** [comment]
Outdenting isn't handled by the plugin, it's done by the text editor. And in VS Code, this behavior is buggy if `editor.useTabStops` is set to `false`. The only thing Ionide could do, is don't set that option for F# by default. But see microsoft/vscode#27851 for some background what Ionide does this in the first place.

**Comment by stevenybw** [comment]
I see. But comparing with the outdenting problem, I doubt that the problem mentioned in  [microsoft/vscode#27851](https://github.com/microsoft/vscode/issues/27851) is not much significant. The root cause of that case is that VSCode requires fully-aligned to a tab-stop and in that case a semi-tab-stop makes it not aligned. 

```
type X =
    { a : string
      b : string }
```

But this can be solved by this style of type declaration, where each line is aligned to tab-stop:

```
type X = 
    {
        a : string
        b : string 
    }
```

I feel that the problem mentioned above is just a corner case that can be fixed. However, the existing solution introduces a ubiquitous problem that can't be solved and influence the coding efficiency.
