### ISSUE TITLE
Feature request: automatically sort import declarations

### ISSUE THREAD

**Issue by AlexTroshkin** [ionide/ionide-vscode-fsharp#663]
It would be nice if the import declarations were sorted when the file was saved (perhaps it's worth adding it to the settings)

**Comment by Krzysztof-Cieslak** [comment]
Order of `open` declarations in F# is significant. So we cannot automatically sort them.

**Comment by enricosada** [comment]
In F# you cannot do that.

pasting answer from @gerardtoconnor

> The compiler iteratively layers both namespaces and modules into entity resolving map so last declared with conflict should overwrite previous def


that mean:

- for modules, the order of import matter a lot. an easy scenario: a module may for example override (shadow) the behaviour of previous declared function.
An example is you do `open FSharp.Core.Operators.Checked` , this will redefine operators raising expection instead of invalid numbers (https://stackoverflow.com/questions/41684233/overflow-of-an-int-in-f)

- for namespace is not safe either, because last declared entity is used to get resolution

**Comment by enricosada** [comment]
@Krzysztof-Cieslak i was just pressing comment and close :D

**Comment by gerardtoconnor** [comment]
Just add to this, there is a Layered Map implementation that tries to enable fall back resolution but Vasily said not being used atm, presumably due to complexity on type resolver
