### ISSUE TITLE
Ionide Intellisense not recognizing Nuget Packages

### ISSUE THREAD

**Issue by robertmaxton42** [ionide/ionide-vscode-fsharp#697]
I'm having trouble getting Ionide to recognize packages outside .NET. For example, FParsec:

https://imgur.com/242w0BS

As with #421, I can build fine, but the solution listed there doesn't seem to work for me - while I didn't have MSBUILD_TOOLS added as a variable the first time, I've added it and then reinstalled Ionide, and then Code entirely and the problem persists.

**Comment by Krzysztof-Cieslak** [comment]
Can you share the project file (and Paket files if you use it)

**Comment by robertmaxton42** [comment]
Sure. Zip contains the .fsproj, paket.references, paket.lock, paket.dependencies, and for bonus points the .fs file in my screenshot above (there isn't actually any more code than is visible but I thought it might be handy), directory tree structure preserved.

**Comment by robertmaxton42** [comment]
Sure. Zip contains the .fsproj, paket.references, paket.lock, paket.dependencies, and for bonus points the .fs file in my screenshot above (there isn't actually any more code than is visible but I thought it might be handy), directory tree structure preserved.

[IonideDebug.zip](https://github.com/ionide/ionide-vscode-fsharp/files/1636541/IonideDebug.zip)

**Comment by enricosada** [comment]
let me check

**Comment by enricosada** [comment]
@robertmaxton42 i tried locally, the repro works for me locally after some changes.

First, the file `Parser.fs` was not included in the fsproj https://github.com/enricosada/IonideDebug_697/commit/0df74bec84108bb46fc21949ae8227b1fe4f5deb

And you shouldnt use `<Reference Include="FParsec` because that's to reference the assemblies in GAC, just remove it https://github.com/enricosada/IonideDebug_697/commit/ceceff26eb21290e068bfea09936cf695b7a40b6

as a note, i tried with .net 4.6.2, not 4.7.1 because i dont have it (https://github.com/enricosada/IonideDebug_697/commit/02a7c847d93ffaf0739a339a1110ee5153b3d769)

Can you please check on bottom left, in the `F#: solution explorer` if the project is loaded correctly, if reference and files are correct, like this 
![image](https://user-images.githubusercontent.com/147243/35041139-0016b61a-fb84-11e7-9158-ee42e6834c5d.png)

**Comment by robertmaxton42** [comment]
Yep, that fixed it. The first one, that is, though I took out the FParsec reference in the fsproj just to be safe. Thanks for the help!
