### ISSUE TITLE
Intellisense stops working after Mono upgrade

### ISSUE THREAD

**Issue by duncanmak** [ionide/ionide-vscode-fsharp#735]
I saw that Intellisense stopped running after a Mono upgrade - I think this is due to the fact that the background server uses prebuilt binaries to find additional assemblies.

For example, if my project was compiled using Mono 5.4, and then I upgraded to Mono 5.8 (and deleted 5.4), then Ionide will try to load `System.dll` and friends from `/Library/Frameworks/Mono.framework/Versions/5.4.1`, and not the newly available `/Library/Frameworks/Mono.framework/Versions/5.8.0`.

You can fix this by deleting the built-tree.

**Comment by Krzysztof-Cieslak** [comment]
This happens because we use persistent caching of project parsing results to ensure fast Ionide (or rather FSAC) startup. After update of mono paths of dlls has changed indeed, so our cached results are wrong - solution to that is running `F#: Clear Cache` command and reloading the window.

I think it's exceptional situation (i.e users don't update mono on daily basis), and fix for it wouldn't be easy - we would need to make some heuristics, inspect if mono paths still exists, etc on every startup. Which IMO is not worth potential problems, maintaing cost. So closing the issue as `by-design`
