### ISSUE TITLE
Get Ionide logs failure.

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#753]
https://imgur.com/a/aEdBD

Reported by @landy on Twitter.

CC: @MangelMaxime

**Comment by MangelMaxime** [comment]
I think the problem is coming from https://github.com/ionide/ionide-vscode-fsharp/blob/12c263901638e7f01ceba5e786c911df1a8dd8a9/src/Components/Diagnostics.fs#L211

I was thinking that `Exports.Os.homedir()` was able to find the `HOME` dir on windows, but not sure if all the Windows OS have it by default.

Also, I think we should use `Exports.Os.tmpdir()` instead of `Exports.Os.homedir()` like that the logs will be cleaned by the OS when needed. For now, they are written and never cleaned.

I can send a PR tomorrow, however I am not sure to have access to a Windows computer..

**Comment by landy** [comment]
Let me know if I can help you with something
