### ISSUE TITLE
Member signature missing arrow, looks like property

### ISSUE THREAD

**Issue by klettier** [ionide/ionide-vscode-fsharp#814]
Hello,

Ionide version: **3.20.4**

![image](https://user-images.githubusercontent.com/3425823/40172969-82ec00ae-59d0-11e8-8bca-51650c423961.png)

**Comment by Krzysztof-Cieslak** [comment]
@priort, any ideas?

**Comment by priort** [comment]
Damn, most likely from my change to make getter signatures the same as code lens
https://github.com/fsharp/FsAutoComplete/commit/c5c8e0d4766b6a5d1e6d62a1258fa3a148a8566e

This check here ```symbol.IsPropertyGetterMethod```
that probably includes methods as well as properties - there is probably something else on the symbol that we can check instead.
I don't have FSAC on my machine at the moment but hopefully I'll get a chance on the weekend to check it out again and fix this.

**Comment by priort** [comment]
I'm not totally sure yet if its related to my fix for this https://github.com/ionide/ionide-vscode-fsharp/issues/789

It seems fine on class members.
<img width="406" alt="member-getter" src="https://user-images.githubusercontent.com/13556648/40272906-dff5951a-5bad-11e8-863c-9014757541fc.png">
Also the abstract member signature itself seems fine:

<img width="446" alt="abstract-member-signature" src="https://user-images.githubusercontent.com/13556648/40272929-a0ae74f2-5bae-11e8-855b-3f87d2dade3a.png">

But I see the issue on implementations of abstract members:
<img width="445" alt="interface-member-impl" src="https://user-images.githubusercontent.com/13556648/40272909-f9253b44-5bad-11e8-949a-2a02437c97db.png">
I'll have to debug in FSAC to investigate what's happening with interface member implementations signatures.

**Comment by priort** [comment]
on ```override __.Y() = 4```, the IsPropertyGetterMethod on the symbol in fsac returns false
<img width="706" alt="ispropgetteronoverride" src="https://user-images.githubusercontent.com/13556648/40273270-29de2b22-5bb5-11e8-8222-7efa0aac2dc9.png">

<img width="603" alt="ispropgetter-2" src="https://user-images.githubusercontent.com/13556648/40273300-a727b7f6-5bb5-11e8-8078-6b68e60fa5c8.png">
So it doesn't look like this issue is due to the IsPropertyGetterMethod check that I added.
 I think its happening later on in the processing in FSAC. I'll investigate more tomorrow or in next day or so.

**Comment by priort** [comment]
@klettier @Krzysztof-Cieslak 
I fixed the issue on FSAC and put in a PR here https://github.com/fsharp/FsAutoComplete/pull/293
The PR has screenshots of the fix in action.

**Comment by Krzysztof-Cieslak** [comment]
Released in `3.20.5`

**Comment by priort** [comment]
Cool, thanks!
